using System.Text;
using RcaEngine.Models;

namespace RcaEngine.Reporting;

public static class MarkdownReportRenderer
{
    public static string Render(RcaReport report)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# RCA Report — {report.IncidentId}");
        sb.AppendLine();
        sb.AppendLine($"| | |");
        sb.AppendLine($"|---|---|");
        sb.AppendLine($"| **Node** | {report.NodeId} |");
        sb.AppendLine($"| **Failing subsystem** | {report.Category} |");
        sb.AppendLine($"| **Failing component** | {report.FailingComponent} |");
        sb.AppendLine($"| **Confidence** | {report.Confidence:P0} |");
        sb.AppendLine($"| **Generated by** | {report.GeneratedBy}{(report.ModelId is not null ? $" ({report.ModelId})" : "")} |");
        sb.AppendLine($"| **Triage duration** | {report.TriageDurationSeconds}s |");
        sb.AppendLine($"| **Generated at** | {report.GeneratedAt:u} |");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine(report.Summary);
        sb.AppendLine();
        sb.AppendLine("## Root Cause");
        sb.AppendLine(report.RootCause);
        sb.AppendLine();
        sb.AppendLine("## Customer Impact");
        sb.AppendLine(string.IsNullOrWhiteSpace(report.CustomerImpact) ? "_Not assessed._" : report.CustomerImpact);
        sb.AppendLine();
        sb.AppendLine("## Evidence");
        if (report.Evidence.Count == 0) sb.AppendLine("_None recorded._");
        foreach (var item in report.Evidence)
            sb.AppendLine($"- **[{item.Source}]** {item.Detail}");
        sb.AppendLine();
        sb.AppendLine("## Recommended Actions");
        if (report.RecommendedActions.Count == 0) sb.AppendLine("_None recorded._");
        for (var i = 0; i < report.RecommendedActions.Count; i++)
            sb.AppendLine($"{i + 1}. {report.RecommendedActions[i]}");
        return sb.ToString();
    }
}
